[package]
name = "api_version"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "1.3.2"
cells_utils = {path = "../cells_utils"}
cells_types = {path = "../cells_types"}